name: CI
on: [push, pull_request]
env:
  go-version: '1.14.x'
jobs:
  test:
    name: Test
    strategy:
      matrix:
        pg-version: ['10', '11']
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ env.go-version }}

    - name: Run tests
      run: go test -coverprofile=coverage.text -covermode=atomic ./...
